---
# v1
- name: 安装 git
  ansible.builtin.apt:
    name: git
    state: present

- name: Clone yattee-server 源码  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/yattee/yattee-server.git
    dest: "{{ yattee_install_dir }}"
    update: true

- name: 渲染 yattee-server 环境变量文件
  ansible.builtin.template:
    src: yattee.env.j2
    dest: "{{ yattee_install_dir }}/.env"
    mode: '0600'
  notify: 重启 yattee-server

- name: 启动 yattee-server 容器[第一次需要较长时间，约5-10分钟，耐心等待]
  ansible.builtin.command:
    cmd: docker compose up -d --build
    chdir: "{{ yattee_install_dir }}"
  register: application_yattee_compose_result
  changed_when: "'Started' in application_yattee_compose_result.stdout or 'Recreated' in application_yattee_compose_result.stdout"

- name: 部署 yattee Nginx server 配置
  ansible.builtin.template:
    src: nginx-yattee.conf.j2
    dest: "/etc/nginx/conf.d/{{ yattee_domain }}.conf"
    mode: '0644'
  notify: Reload nginx

- name: 部署 yattee-update systemd service
  ansible.builtin.template:
    src: yattee-update.service.j2
    dest: /etc/systemd/system/yattee-update.service
    mode: '0644'

- name: 部署 yattee-update systemd timer
  ansible.builtin.template:
    src: yattee-update.timer.j2
    dest: /etc/systemd/system/yattee-update.timer
    mode: '0644'

- name: 启动并启用 yattee-update timer
  ansible.builtin.systemd:
    name: yattee-update.timer
    state: started
    enabled: true
    daemon_reload: true
