---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    state: restarted
    enabled: true
