---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    state: restarted
    enabled: true
